### ISSUE TITLE
v0.2.2 does not work with solid start

### ISSUE THREAD

**Issue by NorbertBodziony** [wobsoriano/solid-sonner#4]
Seems like something it wrong with v0.2.2 in combination with solid-start+tailwind.
Toasters are not rendered correctly.

v0.2.0 works just fine.

**Comment by wobsoriano** [comment]
Havent updated solid sonner for a long time I guess but sure will this weekend!

**Comment by wobsoriano** [comment]
I forgot to inject the styles lol. It should be fixed now.

Plus don't forget to check out the README! Added more features and stuff :)

**Comment by NorbertBodziony** [comment]
thanks 
you are real giga chad
